FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
S2I_SOURCE_DEPLOYMENTS_FILTER=*-runner.jar
COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/